### ISSUE TITLE
What did you think about the process of writing a command?

### ISSUE THREAD

**Issue by danielbachhuber** [markri/wp-sec#1]
What went well, and what could be improved? Any documentation changes you'd suggest?

**Comment by markri** [comment]
First of all; thnx for merging my package in the package index.

The scaffolding package is very helpfull for a quick start and documentation gives a pretty good explanation about integration.

Most confusing part was about dependency management during development. An example in documentation would be nice. Like noting that you could use external dependencies inside your package with composer and then how to handle autoloading these during development. (or I'm getting it wrong)

Also concerning dependencies: I still get an error during the install when running `wp package install markri/wp-sec`

Error: guzzlehttp/guzzle 6.2.x-dev requires guzzlehttp/promises ^1.0 -> satisfiable by guzzlehttp/promises[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.1.0, 1.2.0, 1.0.x-dev].

I tried adding promises in composer.json (although it doesn't make sense as it should install dependencies recursively), but didn't help. Weirdest thing is that although an error is raised, promises is still installed, and the command runs perfectly without any errors. Any idea?

**Comment by danielbachhuber** [comment]
> The scaffolding package is very helpfull for a quick start and documentation gives a pretty good explanation about integration.

Glad to hear :)

> Most confusing part was about dependency management during development. An example in documentation would be nice. Like noting that you could use external dependencies inside your package with composer and then how to handle autoloading these during development. (or I'm getting it wrong)

Dependency management should work as you'd expect it to work with any other Composer project. Could you explain more how this is confusing?

> Weirdest thing is that although an error is raised, promises is still installed, and the command runs perfectly without any errors. Any idea?

This isn't actually an error :( The messaging is incorrect. I've created an issue for it: https://github.com/wp-cli/wp-cli/issues/3417

**Comment by markri** [comment]
Concerning dependency management; the autoloader is in a different place while developing compared to an installation in wp-cli. This is my fix for now..

https://github.com/markri/wp-sec/commit/d1876ce45f4a3e8a737b5a7a02d57221224f97dc

Glad to hear it's a known issue and that it is adressed :-)
