### ISSUE TITLE
Ignore list feature suggestion.

### ISSUE THREAD

**Issue by cericoda** [markri/wp-sec#15]
It might be nice to be able to maintain an 'ignore list' of vulnerabilities to ignore. In particular, 2017-8295 is still present in Wordpress but can and is often mitigated by the Apache configuration. By supplying an ignore list as an argument, it would be possible to have such a site come up clean.

For some reason, checking wordpress 4.8.2 results in the return of two entries of this 2017-8295 CVE.

**Comment by cericoda** [comment]
Thinking about this, this might be better handled by a wrapper script, external to the plugin, The reason why I thought this might be worth doing was due to the nagios-type output, if using with nagios, you might want some way to control this.

I have just been writing a python script to do this, and realised that not all vulnerabilities have a CVE, so had to do it based on 'title' instead.

**Comment by markri** [comment]
cool! And yes, that would surely be a better solution, to wrap it in another script. You could use the JSON output for that, but you probably already figured that out :-)
