### ISSUE TITLE
dropin plugins

### ISSUE THREAD

**Issue by cericoda** [markri/wp-sec#26]
Hi I have just run wp-sec check (version 0.0.2) against wp-cli version 2.0.1 on a multisite and the plugin errored out:

Error: Unexpected response from wpvulndb for plugin sunrise.php

Sure enough, `wp plugin list` now shows dropin plugins as well as 'must-use' in the list [thanks to this commit](https://github.com/wp-cli/extension-command/commit/5e1f056ded5999f876ca5713b09716a25075f830).

example end of plugin output:-
```
| admin-menu-editor-mu               | must-use       | none      |         |
| advanced-cache.php                 | dropin         | none      |         |
| sunrise.php                        | dropin         | none      |         |
+------------------------------------+----------------+-----------+---------+
```

Of course, these aren't going to be present on wpvulndb not least because they don't appear to have versions either.

I thought this might be an easy fix but I had a look at the wp plugin list command and can't see how to skip displaying dropin plugins. 

EDIT: So I have now added a condition to exclude those plugins with a pull request which has worked fine on my example site.

**Comment by wilei** [comment]
As I commented to the PR: I've tested this patch with WP-CLI 2.0.1 and WP-sec 1.0.3. With this patch, check works when there's sunrise.php in place. The site has plugins with both, dropin and must-use, statuses.

**Comment by markri** [comment]
Thnx!
