### ISSUE TITLE
Issue parsing maintenance.php (the WP core file)

### ISSUE THREAD

**Issue by cinghaman** [markri/wp-sec#28]
While running the command, I am getting this error from the core file, maintaince.php

Vulnerabilities:
Error: Unexpected response from wpvulndb for plugin maintenance.php

WP version 5.2.2
 wp wp-sec Version: 0.0.2

**Comment by 0x6d617474** [comment]
I have the same issue: 

```
$ wp wp-sec check --type=plugins

-------------------------------
Checking plugin vulnerabilities
-------------------------------

Vulnerabilities:
-----------------------------
Error: Unexpected response from wpvulndb for plugin maintenance.php

$ wp wp-sec version
Version: 1.0.0
```

**Comment by cinghaman** [comment]
Closing this, as I moved onto a different solution
