### ISSUE TITLE
API fees

### ISSUE THREAD

**Issue by cericoda** [markri/wp-sec#29]
Not an issue but a question for discussion if that's ok.

Using this plugin on a few sites even with caching won't be possible without obtaining an enterprise license the provider. 

I have about 35 sites I check daily which causes over 3 times the 250 query limit. I have made enquiries on the pricing but it's a little too expensive for just me to pay.

Has anyone got any ideas about how we could collaborate around this project to get better value than everyone having to buy an enterprise license?

**Comment by markri** [comment]
I think it was just a matter of time when they were charging fees for it. As I do understand they need to cover their costs, I don't understand it from a security  point of view. It's a self fullfilling prophecy, no fee provides more users (and will attract more additinal users) as charging a fee doesn't. But this is too easy for me to say. I don't need to operate their company, so they might have a valid reason for it. We all need to make money right?

On the other hand, more ethical oriented, this doesn't make the world a safer place. As a strong believer in open source and free information, I do believe that the data itself should be free of charge to make the wp world safer.

Time will tell, allthough it doesnt look very promising right now. I guess we have to go for the long run.

Regarding your question, I don't think we should collaborate in creating a public cache of their database (where the needed solution will lead to, to prevent spending some fees). Their database is probably protected by copyright. I don't want to violate any licence for that matter.

The only way to overcome this (IMO) is to persuade wpvulnb to open up their data (not services) and give it to the community. But it will probably a tough sell as they are currently moving to the other side. 

----
Edited this message: as I didnt lookup the actual fee before writing this. When I came to know the actual fee, I realized its quite reasonable when looking at the volume you get for that

**Comment by cericoda** [comment]
OK, well I was told that an enterprise license is €40 per month, for unlimited queries. I was actually thinking it would make sense to set up a syndicate to share this enterprise key. Probably not permitted, and quite a bit of work to manage.

Have you enquired how much it would cost to license the wp-sec plugin? possibly could set up a patreon or something to cover the fee if enough people are interested. I like the fact I can script stuff so I only get the information I need.

Anyway after intensive searching I have realised that for me, the managewp bundles is probably the way to go, they charge $25 per month for per 100 sites for security scanning and bundle quite a few features in including being able to update from their console, and add new sites and log into sites easily over slack.
