### ISSUE TITLE
Undefined variable when cache is used.

### ISSUE THREAD

**Issue by ABCdatos** [markri/wp-sec#32]
When getting a cached response from wpvulndb, this happens:

`PHP Notice:  Undefined variable: url in /usr/local/lib/wp-cli-packages/vendor/markri/wp-sec/command.php on line 225`

This adds the variable value with a 'Cached' string.

[command-patch.txt](https://github.com/markri/wp-sec/files/3827705/command-patch.txt)

**Comment by markri** [comment]
Agreed, just implemented your patch in master
