### ISSUE TITLE
wpvulndb.com api v2 is dead

### ISSUE THREAD

**Issue by khag7** [markri/wp-sec#33]

**Comment by aaronmweiss** [comment]
I believe I'm experiencing something similar. I've been getting the following when I run this command:

`-----------------------------------------------
Checking core vulnerabilities for version 5.3
-----------------------------------------------

Error: Couldn't check wpvulndb @ https://wpvulndb.com/api/v2/wordpresses/53 (HTTP code 404)`

**Comment by markri** [comment]
Just removed the APIv2 methods. APIv3 is now default and requires the usage of --token on the commandline. It will error if you omit the parameter.

**Comment by khag7** [comment]
seems reasonable. thanks dude!

**Comment by aaronmweiss** [comment]
Thank you for the quick turn around. I'm now recieving a 401 error when I run with v3 and my token:


![2019-11-26_17-04-22](https://user-images.githubusercontent.com/38088034/69680004-4a2b7e00-106f-11ea-8240-d25e8e25048e.jpg)

**Comment by markri** [comment]
Could you try without the brackets? [ ]

**Comment by aaronmweiss** [comment]
Yep, that worked. I guess I was a little confused by the manual. Thank you.
